<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ouyunc</groupId>
        <artifactId>ouyunc-commons</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>ouyunc-id</artifactId>
    <name>ouyunc-id</name>
    <version>${revision}</version>
    <description>全局递增唯一id生成模块</description>


    <dependencies>
        <!-- cosId 核心 + 雪花算法 -->
        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-core</artifactId>
        </dependency>
        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ouyunc</groupId>
            <artifactId>ouyunc-cache</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

</project>