spring:
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/database?authSource=admin
      database: your_database
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      grid-fs-database: your_gridfs_database
      repositories:
        type: auto
      uuid-representation: standard