<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ouyunc</groupId>
        <artifactId>ouyunc-commons</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>ouyunc-mq</artifactId>
    <description>消息队列工具模块</description>
    <packaging>pom</packaging>
    <modules>
        <module>ouyunc-mq-kafka</module>
        <module>ouyunc-mq-rocket</module>
    </modules>


</project>