<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ouyunc</groupId>
        <artifactId>ouyunc-db</artifactId>
        <version>6.0.0</version>
    </parent>
    <artifactId>ouyunc-db-mysql</artifactId>
    <description>mysql模块</description>

    <properties>
        <mysql.version>9.0.0</mysql.version>
        <sprig-jdbc.version>6.2.1</sprig-jdbc.version>
        <hikari.version>6.2.1</hikari.version>
    </properties>

    <dependencies>
        <!-- HikariCP -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>${hikari.version}</version>
        </dependency>

        <!-- Spring JDBC (用于JdbcTemplate) -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <version>${sprig-jdbc.version}</version>
        </dependency>

        <!-- MySQL驱动 -->
        <!-- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.version}</version>
        </dependency>

    </dependencies>

</project>